### ISSUE TITLE
Tab characters not escaped.

### ISSUE THREAD

**Issue by Josee9988** [jpoehls/vscode-json-escaper#2]
Hi sir, I've just used your extension and It simply does what it is supposed to do, but I think you could improve it by escaping tab characters.

Example: 
https://i.imgur.com/oXeyI0L.png

As you can see it just add a lot blank spaces instead of using two or three `\t`.

It makes the json **bigger** in size and **slower**.

Thanks for the extension!

**Comment by jpoehls** [comment]
Thanks for taking the time to mention this. I finally got around to testing it and I wasn't able to reproduce. I'm using `JSON.stringify()` to escape the string so this behavior may have changed in a recent VS Code update due to them upgrading the underlying version of Chrome? Not sure.

Feel free to re-open if you are still seeing this behavior in VS Code 1.44.1 or newer.

Here is what I tested with:

-------

Before:

```plain
{
	try {
		"hi"
	}
}
```

After escaping:

```plain
{\n\ttry {\n\t\t\"hi\"\n\t}\n}
```
